### ISSUE TITLE
Uninstalling aliases app

### ISSUE THREAD

**Issue by newtonkiragu** [newtonkiragu/aliases#7]
**Describe the bug**
When you uninstall aliases using the `rmalias` command, it keeps on prompting you to install it again every time you open the terminal.

**To Reproduce**
1. run `rmalias` in your terminal
2. open a new terminal instance
3. See error

**Expected behavior**
It is expected that once you uninstall the application, it is completely removed from your system.

**Desktop:**
 - OS: Deepin
 - Terminal console: bashrc
 - Version: 15.9

**Comment by tgalvinjr** [comment]
It also does not delete the cron job it created when you run the ```rmaliases``` command
